package eu.revevol.calendar.model;

import com.googlecode.objectify.annotation.*;
import eu.revevol.calendar.constants.ACLStatus;
import java.util.Date;

/**
 *
 * @author Clement <clement.hannicq@revevol.eu>
 */
@Entity
@Cache
public class ACL {

    /**
     * Autogenerated
     */
    @Id public Long id;

    /**
     * Mail
     */
    @Index public String user;

    /**
     *
     */
    @Index public Long location;

    /**
     * Enum with values PENDING,USER,ADMIN
     */
    @Index public ACLStatus status;
    
    public Date last;
}
