package eu.revevol.calendar.model;

import com.googlecode.objectify.annotation.*;

/**
 *
 * @author Clement <clement.hannicq@revevol.eu>
 */
@Entity
@Cache
public class Asset {
    @Id public Long id; //autogenerated
    public String type;
    public String name;
    public String notes;
    public int r;
    public int g;
    public int b;
    @Index public boolean active;
    @Index public String os;
}
