package eu.revevol.calendar.model;

import com.googlecode.objectify.annotation.*;

/**
 *
 * @author Clement <clement.hannicq@revevol.eu>
 */
@Entity
@Cache
public class Location {
    @Id public Long id; //Autogenerated
    public String name;
    
    public Boolean deleted;
}
