package eu.revevol.calendar.model;

import com.googlecode.objectify.annotation.*;
import java.util.Date;

@Entity
@Cache
public class Purpose {
    @Id public Long id; //autogenerated
    @Index public String person;
    @Index public String type; // App / Web
    public String title;
    @Index public boolean deleted = false;
    @Index public Date dateUpdate;
}
